name: rivedpod_clone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_ui_auth: ^1.13.1
  firebase_ui_firestore: ^1.6.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.4
  mocktail: ^1.0.3
  random_string: ^2.3.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.8
  custom_lint: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # a tool for running code generators
  # the code generator
  # riverpod_lint makes it easier to work with Riverpod
  # import custom_lint too as riverpod_lint depends on it

flutter:
  uses-material-design: true
  # assets:
  #   - assets/time-tracking.svg