name: appwrite_twitter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  appwrite: ^11.0.1
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  like_button: ^2.0.5
  timeago: ^3.6.1
  any_link_preview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
